name: cafe_connect
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cloud_firestore:
  cupertino_icons: ^1.0.2
  firebase_analytics:
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  lottie:
  shared_preferences: ^2.0.7
  url_launcher:
  cached_network_image:
  animated_splash_screen:
  page_transition:

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.jpg"
